x = + prompt("number")
y = + prompt("number")
document.getElementById("sum").innerHTML=`<h1> sum:${ x + y} </h1>`
document.getElementById("sub").innerHTML=`<h1> sub:${ x - y} </h1>`
document.getElementById("div").innerHTML=`<h1> div:${ x / y} </h1>`
document.getElementById("mul").innerHTML=`<h1> mul:${ x * y} </h1>`
document.getElementById("pow").innerHTML=`<h1> pow:${ x ** y} </h1>`
document.querySelector(".class").innerHTML=`wowo`
document.getElementById("idm").innerHTML=`koko`
document.querySelector("div#idid").innerHTML=`lolo`
document.querySelector("#id").innerHTML=`uouo`
root=document.getElementById("root")
root.style.width="400px"
root.style.height="400px"
root.style.margin="20px auto"
root.style.backgroundColor="#2b2b2b"
root.style.border="2px solid red"
root.style.borderRadius="30px"